<?php
if (session_status() === PHP_SESSION_NONE)
    session_start();
include("config.php");

if (!isset($_SESSION['user_id'])) {
    header("Location: index.php");
    exit();
}

$user_id = (int) $_SESSION['user_id'];

require("fpdf/fpdf.php");

// ===== TOTALS =====
$stmt = $conn->prepare("SELECT COUNT(*) as total FROM tasks WHERE user_id=?");
$stmt->bind_param("i", $user_id);
$stmt->execute();
$total = $stmt->get_result()->fetch_assoc()['total'] ?? 0;

$stmt = $conn->prepare("SELECT COUNT(*) as completed FROM tasks WHERE user_id=? AND status='completed'");
$stmt->bind_param("i", $user_id);
$stmt->execute();
$completed = $stmt->get_result()->fetch_assoc()['completed'] ?? 0;

$pending = $total - $completed;
$percent = ($total > 0) ? round(($completed / $total) * 100) : 0;

// ===== SUBJECT BREAKDOWN =====
$stmt = $conn->prepare("
SELECT subjects.name, COUNT(tasks.id) as total
FROM tasks
JOIN subjects ON tasks.subject_id = subjects.id
WHERE tasks.user_id=?
GROUP BY subjects.id
");
$stmt->bind_param("i", $user_id);
$stmt->execute();
$subjectData = $stmt->get_result();

// ===== USER INFO =====
$stmt = $conn->prepare("SELECT name, email FROM users WHERE id=? LIMIT 1");
$stmt->bind_param("i", $user_id);
$stmt->execute();
$user = $stmt->get_result()->fetch_assoc();

$pdf = new FPDF();
$pdf->AddPage();

// ===== HEADER =====
$pdf->SetFillColor(102, 126, 234);
$pdf->SetTextColor(255, 255, 255);
$pdf->SetFont("Arial", "B", 18);
$pdf->Cell(0, 15, "Study Planner Progress Report", 0, 1, "C", true);

$pdf->Ln(5);
$pdf->SetTextColor(0, 0, 0);
$pdf->SetFont("Arial", "", 12);

$pdf->Cell(0, 8, "Name: " . ($user['name'] ?? "User"), 0, 1);
$pdf->Cell(0, 8, "Email: " . ($user['email'] ?? "-"), 0, 1);
$pdf->Cell(0, 8, "Generated on: " . date("d M Y"), 0, 1);

$pdf->Ln(8);

// ===== SUMMARY TABLE =====
$pdf->SetFont("Arial", "B", 12);
$pdf->Cell(60, 10, "Total Tasks", 1, 0, "C");
$pdf->Cell(60, 10, "Completed", 1, 0, "C");
$pdf->Cell(60, 10, "Pending", 1, 1, "C");

$pdf->SetFont("Arial", "", 12);
$pdf->Cell(60, 10, $total, 1, 0, "C");
$pdf->Cell(60, 10, $completed, 1, 0, "C");
$pdf->Cell(60, 10, $pending, 1, 1, "C");

$pdf->Ln(8);

// ===== PROGRESS BAR =====
$pdf->SetFont("Arial", "B", 12);
$pdf->Cell(0, 10, "Overall Progress: " . $percent . "%", 0, 1);

$barWidth = 180;
$progressWidth = ($percent / 100) * $barWidth;

$pdf->SetFillColor(230, 230, 230);
$pdf->Cell($barWidth, 8, "", 0, 1, true);

$pdf->SetY($pdf->GetY() - 8);
$pdf->SetFillColor(46, 204, 113);
$pdf->Cell($progressWidth, 8, "", 0, 1, true);

$pdf->Ln(12);

// ===== SUBJECT BREAKDOWN =====
$pdf->SetFont("Arial", "B", 14);
$pdf->Cell(0, 10, "Subject-wise Breakdown", 0, 1);

$pdf->SetFont("Arial", "B", 12);
$pdf->Cell(120, 10, "Subject", 1);
$pdf->Cell(60, 10, "Tasks", 1, 1, "C");

$pdf->SetFont("Arial", "", 12);
while ($row = $subjectData->fetch_assoc()) {
    $pdf->Cell(120, 10, $row['name'], 1);
    $pdf->Cell(60, 10, $row['total'], 1, 1, "C");
}

// ===== FOOTER =====
$pdf->Ln(15);
$pdf->SetFont("Arial", "I", 10);
$pdf->Cell(0, 10, "Generated by Study Planner System", 0, 0, "C");

$pdf->Output("D", "study_planner_report.pdf");